### ISSUE TITLE
Can using this program result in a ban?

### ISSUE THREAD

**Issue by JhogerZk** [T2hhbmEK/genshin-clicker#1]
I would like to know if there are cases of banning or if it is totally safe

**Comment by T2hhbmEK** [comment]
Use it at your own risk!

I don’t think any games nowadays allow any kinds of third-party automations in its terms. However little of non-competitive games actually ban users for using auto clickers. 

So far I haven’t been banned. 

However I have been AFK from Genshin Impact for months now. So let me know if it no longer works.

The script does not temper with any data. It just watch your PC screen and click the button for you.
