### ISSUE TITLE
Error when using

### ISSUE THREAD

**Issue by xilostcause** [T2hhbmEK/genshin-clicker#2]
Hi there,

Thanks for your script to help navigate dialogue in this game. I noticed a problem where sometimes the text box for dialogue will shift upwards putting any type of dialogue choices that need to be clicked too high for wherever the cursor is programmed to click. 

I've edited auto-hotkey files before but unfortunately this doesn't open in NotePad. Is there a way this can be edited or let me know how I can do it?

Thanks!

**Comment by T2hhbmEK** [comment]
The executable you downloaded from release page is compiled one without user to preinstall autohotkey. The source code is available in the repository ends with .ahk. 
https://github.com/T2hhbmEK/genshin-clicker/blob/main/GenshinClicker.ahk

**Comment by xilostcause** [comment]
Thank you. Unfortunately your coding is way more complicated than I anticipated for an auto-clicker. I see an "DetectOptionOffset" but not sure if this is the correct part of the coding or how to even alter it. If you have any intentions of updating or have any ideas on how to fix this issue with it program, please let me know! 

Basically whenever the height of the dialogue box increases (too much text on the screen), any type of dialogue option that you must select is not being selected.

Appreciate it!
