### ISSUE TITLE
fix text overflow

### ISSUE THREAD

**Issue by T2hhbmEK** [T2hhbmEK/genshin-clicker#3]
Thank you. Unfortunately your coding is way more complicated than I anticipated for an auto-clicker. I see an "DetectOptionOffset" but not sure if this is the correct part of the coding or how to even alter it. If you have any intentions of updating or have any ideas on how to fix this issue with it program, please let me know! 

Basically whenever the height of the dialogue box increases (too much text on the screen), any type of dialogue option that you must select is not being selected.

Appreciate it!

_Originally posted by @xilostcause in https://github.com/T2hhbmEK/genshin-clicker/issues/2#issuecomment-2143648413_

**Comment by T2hhbmEK** [comment]
The text overflow may cause the button position to change unpredictably. A more general button detector should be used. Now the script is only monitoring some fixed-position pixels which is not enough to counter these corner cases.

**Comment by T2hhbmEK** [comment]
@xilostcause pls post some screenshots of these cases. It helps me a lot. It is not easy for me to reproduce it.

**Comment by xilostcause** [comment]
![image](https://github.com/T2hhbmEK/genshin-clicker/assets/112831903/eea0ff22-2863-4f24-8f8a-eb460e1d3195)

This an example where the clicker stops working. Once I manually select the dialogue option it goes back to normal.

**Comment by T2hhbmEK** [comment]
@xilostcause I found a good project that automate more than dialogs.
https://github.com/babalae/better-genshin-impact
It's doing all the tedious jobs for you using computer vison technologies.
However it still got only Chinese documents.
I'm not going to update this project anymore because of having this fantastic alternative.
I might try to help translations of that project and support multi-language if got some spare time.
